# Generated by Django 3.2.12 on 2023-08-20 02:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('address1', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=60)),
                ('zipcode', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US', unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
